stages:
  - build
  - publish

build:
  stage: build
  image: docker:latest
  only:
    - main
  rules:
    - if: $CI_COMMIT_TAG
  services:
    - docker:dind
  before_script:
    - echo BUILD_JOB_ID=$CI_JOB_ID >> build.env
  script:
    - echo "Running build job for $CI_COMMIT_TAG"
    - mkdir -p assets/windows
    - mkdir -p image
    - docker run --rm -v "$(pwd):/src/" "cdrx/pyinstaller-windows:python3" "pyinstaller --onefile src/windows/docker.py --distpath assets/windows"
    - docker run --rm -v "$(pwd):/src/" "cdrx/pyinstaller-windows:python3" "pyinstaller --onefile src/windows/docker-compose.py --distpath assets/windows"
    - DOCKER_BUILDKIT=1 docker build --no-cache --output type=tar,dest=image/wsl-docker-service.tar .
  artifacts:
    expire_in: 1 month
    paths:
      - assets/
      - image/
    reports:
      dotenv: build.env

publish:
  stage: publish
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build
      artifacts: true
  script:
    - echo "Running publish job for $CI_COMMIT_TAG"
  release:
    name: "WSL2 Docker Service $CI_COMMIT_TAG"
    description: "Image and binaries for use Docker in WSL2"
    tag_name: "$CI_COMMIT_TAG"
    ref: "$CI_COMMIT_SHA"
    assets:
      links:
        - name: "docker alias binary"
          url: "https://gitlab.com/codemancers/engineering/cw/-/jobs/${BUILD_JOB_ID}/artifacts/file/assets/windows/docker.exe"
        - name: "docker-compose alias binary"
          url: "https://gitlab.com/codemancers/engineering/cw/-/jobs/${BUILD_JOB_ID}/artifacts/file/assets/windows/docker-compose.exe"
        - name: "wsl2 image"
          url: "https://gitlab.com/codemancers/engineering/cw/-/jobs/${BUILD_JOB_ID}/artifacts/file/image/wsl-docker-service.tar"
